global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bazelbench-rs'
    static_configs:
      - targets: ['localhost:9091']  # Use host.docker.internal for Docker to access the host machine on Mac or Windows
