{
 "title": "Benchmark Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (cache_backend) ( rate(bs_write{success=\"false\"}[$__rate_interval]))",
     "legendFormat": "bs_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (rate(bs_read{success=\"false\"}[$__rate_interval]))",
     "legendFormat": "bs_read {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (rate(ac_write{success=\"false\"}[$__rate_interval]))",
     "legendFormat": "ac_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (rate(ac_read{success=\"false\"}[$__rate_interval]))",
     "legendFormat": "ac_read {{cache_backend}}"
    }
   ]
  },
  {
   "title": "BS GiB Written Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bs_bytes_written_count", "legendFormat": "__auto" },
    {
     "expression": "$bs_bytes_written/1024/1024/1024",
     "type": "math"
    }
   ]
  },
  {
   "title": "BS GiB Read Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bs_bytes_read_count", "legendFormat": "__auto" },
    { "expression": "$bs_bytes_read/1024/1024/1024", "type": "math" }
   ]
  },
  {
   "title": "MAX MiB Write per second",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cache_backend) (rate(bs_bytes_written_count[1m]) / 1024 / 1024)",
     "legendFormat": " {{cache_backend}}"
    }
   ]
  },
  {
   "title": "MAX MiB Read per second",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cache_backend) (rate(bs_bytes_read_count[1m]) / 1024 / 1024)",
     "legendFormat": "{{cache_backend}}"
    }
   ]
  },
  {
   "title": "Bytestream MiB Write and Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expression": "$bs_bytes_read/1024/1024", "type": "math" },
    { "expression": "$bs_bytes_written/1024/1024", "type": "math" }
   ]
  },
  {
   "title": "P95 Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.95, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"bs_write\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "bs_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.95, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"bs_read\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "bs_read {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (histogram_quantile(0.95, sum(rate(response_time_bucket{method=\"ac_write\"}[$__rate_interval])) by (le)))",
     "legendFormat": "ac_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.95, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"ac_read\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "ac_read {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.95, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"cas_find_missing\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "cas_find_missing {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.95, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"get_capabilities\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "get_capabilities {{cache_backend}}"
    }
   ]
  },
  {
   "title": "P50 Response Times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.5, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"bs_write\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "bs_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.5, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"bs_read\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "bs_read {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.5, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"ac_write\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "ac_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.5, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"ac_read\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "ac_read {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.5, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"cas_find_missing\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "cas_find_missing {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (\n    histogram_quantile(0.5, sum by (le, cache_backend) (\n        rate(response_time_bucket{method=\"get_capabilities\"}[$__rate_interval])\n    ))\n)",
     "legendFormat": "get_capabilities {{cache_backend}}"
    }
   ]
  },
  {
   "title": "Bytestream Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg by (cache_backend) (rate(bs_write{success=\"true\"}[$__rate_interval]))",
     "legendFormat": "bs_write {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (rate(bs_read{success=\"true\"}[$__rate_interval]))",
     "legendFormat": "bs_read {{cache_backend}}"
    }
   ]
  },
  {
   "title": "ActionCache Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg by (cache_backend) (rate(ac_read{success=\"true\"}[$__rate_interval]))",
     "legendFormat": "ac_read {{cache_backend}}"
    },
    {
     "expr": "avg by (cache_backend) (rate(ac_write{success=\"true\"}[$__rate_interval]))",
     "legendFormat": "ac_write {{cache_backend}}"
    }
   ]
  },
  {
   "title": "Connect",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg by (cache_backend) (rate(connect{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}